# Generated by Django 4.1.3 on 2024-02-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdiagApp', '0008_rename_slotid_payment_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='prescription',
            field=models.FileField(max_length=200, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='slots',
            name='report',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
