# Generated by Django 4.1.3 on 2024-03-12 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EdiagApp', '0009_alter_slots_prescription_alter_slots_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slots',
            name='test',
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EdiagApp.slots')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EdiagApp.tests')),
            ],
        ),
    ]
