# Generated by Django 4.1.3 on 2024-02-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdiagApp', '0003_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='health',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
