# Generated by Django 4.1.3 on 2024-02-26 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EdiagApp', '0005_slots_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='tsetId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EdiagApp.tests'),
        ),
    ]
