# Generated by Django 4.1.3 on 2024-02-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EdiagApp', '0007_rename_labid_slots_lab_slots_teststatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='slotId',
            new_name='slot',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='slots',
            old_name='tsetId',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='slots',
            old_name='userId',
            new_name='user',
        ),
    ]
